name = "benkyou-server"
compatibility_date = "2025-06-06"
compatibility_flags = [ "nodejs_compat" ]
main = "src/index.ts"
keep_vars = true

[[hyperdrive]]
binding = "HYPERDRIVE"
id = "f28caff3ff8b4d1e8a888a9093587df9"
localConnectionString = "postgresql://postgres:postgres@127.0.0.1:54322/postgres"
